### ISSUE TITLE
simulateResiduals does not work for mgcv::gam when mgcViz is loaded

### ISSUE THREAD

**Issue by wduguid** [florianhartig/DHARMa#144] opened 2020-02-19 00:53 UTC
I find your package extremely useful, thank you. Lately I have been getting an error (pasted below) whenever I attempt to use simulateResiduals with a gam object produced using the mgcv package. A simple example below. I may be missing something very simple. I have seen your responses regarding a similar error message (https://github.com/florianhartig/DHARMa/issues/88) indicating that the problem can be with handling of NA values, but my data to which I am fitting gams have no NAs.

I would be most grateful if you could set me straight!

X<-c(1,2,2,3,2,3,2,3,4,5,6,5,7,5,4,5,6,7,4,4,5,6)
Y<-c(2,3,2,3,2,3,2,3,2,3,6,7,6,8,9,7,6,7,8,7,6,7)
data1<-as.data.frame(cbind(X,Y))
mod<-gam(Y~s(X,k=3),data=data1)
plot(mod,resid=TRUE)
simout  <-  simulateResiduals(mod,  n=1000,plot=T)

Error in securityAssertion("Simulation results have wrong dimension",  : 
  Message from DHARMa package: a security assertion was not met. This means that during the execution of a DHARMa function, some unexpected conditions occurred. Even if you didn't get an error, your results may not be reliable. Please check with the help if you use the functions as intended. If you think that the error is not on your side, I would be grateful if you could report the problem at https://github.com/florianhartig/DHARMa/issues 

 Context: Simulation results have wrong dimension

**Comment by florianhartig** [comment] 2020-02-19 07:50
Hi,

I don't get the same error message. The only response I get is

`Model family was recognized or set as continuous, but duplicate values were detected in the response. Consider if you are fitting an appropriate model.`

which makes sense given your data. Could you maybe try updating mgcv and DHARMa, so that you have the latest versions, and paste a sessionInfo() to see your system?

Best,
Florian

**Comment by wduguid** [comment] 2020-02-19 08:03
Thank you for your response. This was an elementary issue. I had checked that DHARMa was up to date.. but not mgcv. When I updated mgcv the problem disappeared. Thank you!

**Comment by florianhartig** [comment] 2020-02-19 08:46
OK, great!

**Comment by wduguid** [comment] 2020-02-19 18:02
Hello, I hate to say this but strangely the problem has reappeared. All was working well with a variety of different gam objects. I attempted to run simulateResiduals on a new gam object and the same error popped up. Once the error appears once it keeps doing so, even on objects (including my toy example) which had been fine moments before. I have tried restarting R Studio and working directly in R. I am running R version 3.5.1. Perhaps this could be the problem?

**Comment by florianhartig** [comment] 2020-02-20 08:24
Hi, R 3.5.1 is a bit old, but shouldn't be an issue for DHARMa. No idea if mgcv behaves differently with 3.5.1, but if the newest version installs without problem, it should theoretically be supported. 

If you don't mind, could you make a sessionInfo and post or send me a reproducible example, i.e. a chunk of code that produces the error when you start with completely new R session.

**Comment by wduguid** [comment] 2020-02-20 18:20
Hello and Thank you... I think I have a bit more info. The problem was intermittent, and with a new script in a new session I was not getting it, but with the same script in an active session I was getting it. So I sequentially loaded all the libraries I have been using recently one by one until the error appeared. It seems that there may be an incompatibility with the package mgcViz. Here is a short example and the session info pasted below. There should be no error until the mgcViz library loads.

sessionInfo()
library(mgcv)
library(DHARMa)
set.seed(0)
dat<-gamSim(3,n=200,scale=2)
mod<-gam(y~s(x1),data=dat)
simout<-simulateResiduals(mod,n=100,integerResponse=F,plot=T)
library(mgcViz)
mod<-gam(y~s(x1),data=dat)
simout<-simulateResiduals(mod,n=100,integerResponse=F,plot=T)

> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1    yaml_2.2.0

**Comment by florianhartig** [comment] 2020-02-21 18:13
Hi wduguid,

Thanks for your feedback! I overwrite an S3 functions of mgcv because mgcv handles the fitted function differently than other packages, and maybe this is canceled when mgcViz is loaded.

I will try to reproduce this. In the meantime, you could try out if the problem goes away if you load DHARMa as the last package.

**Comment by mikekaminsky** [comment] 2020-04-09 23:55
👋  not much to add here other than that I had the same issue -- not loading `mgcViz` seems to have fixed the issue for me.

**Comment by florianhartig** [comment] 2020-04-10 08:45
OK, I will try to fix this in the next CRAN release, provided that I can find out what exactly the problem is

**Comment by mikekaminsky** [comment] 2020-04-10 14:36
@florianhartig this particular bug seems a bit out of my depth but let me know if I can help :)

**Comment by florianhartig** [comment] 2020-05-10 14:30
OK, I have found the problem. It seems that, very confusingly, mgcViz redefines the simulate function and returns rows and columns swapped. I can possibly check for this, but would probably be better to fix this in mgcViz

```
library(mgcv)
library(DHARMa)

X<-c(1,2,2,3,2,3,2,3,4,5,6,5,7,5,4,5,6,7,4,4,5,6)
Y<-c(2,3,2,3,2,3,2,3,2,3,6,7,6,8,9,7,6,7,8,7,6,7)
data1<-as.data.frame(cbind(X,Y))
mod<-gam(Y~s(X,k=3),data=data1)
plot(mod,resid=TRUE)

dim(simulate(mod))

library(mgcViz)
dim(simulate(mod))
```

**Comment by mfasiolo** [comment] 2020-05-11 11:36
Hi, thanks for letting me know about this. The simulations produced by `mgcViz::simulate.gam()` are now stored by column as in `simulate.lm()`. This will be the default from mgcViz 0.1.7 onwards. See [this commit.](https://github.com/mfasiolo/mgcViz/commit/7794c9ebea97726b686c99cac9c42fc97b9272fe)

**Comment by florianhartig** [comment] 2020-05-11 11:48
OK, thanks Matteo, I will close this. Just out of curiosity - why do you re-define simulate? Does this function behave differently than the mgcv:simulate.gam? Because in this case (or maybe in general), I should both test mgcv and mgcvViz in my unit tests.

**Closed by florianhartig** 2020-05-11 11:48 UTC
Labels: mgcv, minor bug

**Comment by mfasiolo** [comment] 2020-05-11 12:41
No worries. Actually, I don't re-define anything because mgcv::simulate.gam() does not exist!
