### ISSUE TITLE
Influence of sample size on plotResiduals()

### ISSUE THREAD

**Issue by dm807cam** [florianhartig/DHARMa#317] opened 2021-11-19 12:19 UTC
I noticed that the "goodness" of fit suggested by the residuals vs predicted plotResiduals() function depends heavily on sample size. Is this an expected behavior? If so how can this function be considered reliable?

Here is a quick example illustrating what I mean:
 ```{r}
library("tidyverse")
library("mgcv")

set.seed(1804)

# Create sample data
location <- letters[1:15]

dat_long <- tibble(obs=NULL, 
                   location=NULL,
                   des=NULL)

for(ii in 1:length(location)) {

n <- round(runif(1, 50, 100),0)
centr <- round(runif(1, 1, 2),2)
stdev <- round(runif(1, 0.2, 0.7),2)
  
obs <- rnorm(n, centr, stdev)
des <- round(runif(1, centr-stdev, centr+stdev),2)

dat <- data.frame(obs)
dat$location <- as.factor(location[ii])
dat$des <- des

dat_long <- bind_rows(dat_long, dat)
}

# Model data
m1 <- gam(obs ~ s(des), data = dat_long)
# Model subset of 300
m2 <- gam(obs ~ s(des), data = sample_n(dat_long, 300))
```
 ```{r}
# Check residuals with DHARMa
DHARMa::plotResiduals(m1)
```
![res1](https://user-images.githubusercontent.com/20252887/142621623-fa5e4a58-e62d-49f0-8e17-a896babccb47.png)
 ```{r}
DHARMa::plotResiduals(m2)
```
![res2](https://user-images.githubusercontent.com/20252887/142621621-0fe19eb3-9cc5-4873-841a-6786f6f308db.png)

**Comment by florianhartig** [comment] 2021-11-19 12:45
This is expected behaviour for any hypothesis test, as the power of any test increases with the sample size. 

To explain this - note first that DHARMa doesn't measure "goodness" of fit, it is calculating residuals, and then performing additional tests to see if these residuals deviate from a null expectation of a perfect model. 

The residuals for both models look visually quite similar to me. 

However, the model with more data is flagged as significant, while the other is not. To see if the results make sense, we first have to decide: is the model here misspecified or not, i.e. should it be flagged or not? The example you create here is a bit weird, as the gam is flexible and therefore what it predicts may be data-size dependent, but I would still argue that it is very likely that the mode you fit gam(obs ~ s(des), data = dat_long) is misspecified, because it doesn't conform to how you simulated the data. So, the tests on top of the residuals should tell you ideally that there is a pattern, else you are doing a type II error. 

However, to get significance for the test for a pattern (which is measured, in this case, by the qgam package, which is calculating the quantile lines that are displayed in the plot), you will of course need a certain amount of data. The less data you have, the lower the power, and the less likely that qgam sees significant support for a quantile pattern in this data. This is what seems to be happening here. 

So I see nothing weird about the results. If you do a shapiro.test on the residuals of a linear regression, p-values will also decrease if you take only a subset of the residuals. See also comments in the vignette about the interpretation of p-values and hypothesis tests.

**Comment by dm807cam** [comment] 2021-11-19 12:57
Thanks a lot for the explanation. 

Just for the sake of completeness: I refitted my example data with "location" as random effect, assuming that the data reflected repeated samples of something at each location a - o and the quantile pattern disappeared. You are right, the gam for the example data that I used to play with plotResiduals() was poorly chosen. Thanks again! :)

**Comment by florianhartig** [comment] 2021-12-02 13:55
OK, great, will close this!

**Closed by florianhartig** 2021-12-02 13:55 UTC
Labels: question
