### ISSUE TITLE
testSpatialAutocorrelation() produces different results 

### ISSUE THREAD

**Issue by timwilms88** [florianhartig/DHARMa#154] opened 2020-03-27 12:08 UTC
Hi Florian,

I'm facing an issue with testing for spatial and temporal auto-correlation which is a bit similar to issue #108 . In my case, I'm converting simulated predictions (counts) from a Bayesian model to a DHARMa object doing the following:

```{r code1}
D_sim1 <- createDHARMa(simulatedResponse = sim_wide,
                       observedResponse = dat$count,
                       fittedPredictedResponse = med_sim,
                       integerResponse = T)
```
In which `sim_wide` is a matrix with rows for no. of original observations and column for no. of posterior predictions (I'm using 10K simulations, conditional on group-level effects using `re_formula = NULL` in brms). As suggested in the helper file, I am computing the median for each row to use for the `fittedPredictedResponse`, but my counts (and simulations) contain a lot of zero's so the resulting vector consists only of zero's which is my first point of uncertainty.

Since I have a grouping variable, I then test for spatial auto-correlation doing the following:
```{r code2}
D_sp <- recalculateResiduals(D_sim1, group = dat$GroupID)
testSpatialAutocorrelation(D_sp, x= dat2$Lon, y = dat2$Lat, distMat = distM)
```
I am using both coordinates and a distance matrix as input for the test. The coordinates come from a second dataframe with rows for levels of the grouping variable, so they consist of unique coordinates for each grouping variable. The distance matrix consists of UTM distances (in meters) for each pair of observations (GroupIDs) with rownames corresponding to the grouping levels. However, I'm getting different results every time I recalculate the residuals and run the spatial correlation test again. Results vary greatly from a p-value of 0.909 to 0.0034. First I thought this was simply caused by stochastic error so I increased the number of simulations from 1K to 10K already, but it did not provide a more stable outcome. Am I doing something wrong here? I assumed that the outcome of `recalculateResiduals` wouldn't change since I use the same DHARMa object, i.e. simulations, as an input each time and the function would merely restructure the object based on clustering of the grouping variable, but I think I'm missing something. Upon taking a closer look at the Moran's I test output, the `observed` index is different each time I recalculate while the `expected` value remains the same, leading to different p-values each run. 

So my questions are: 
1) Is it okay for the `fittedPredictedResponse` to consist of a vector of zero's only? Or should we rather use the mean prediction in case of a large number of zeros?
2) What could be an explanation for the `observed` index of the Moran's I test being different in my case for every recalculation I compute?

Thanks in advance!

**Comment by florianhartig** [comment] 2020-03-27 19:16
Hi timwilms88,

1. About how to summarise the posterior predictive distribution: of course, the plots, and also the new quantile tests depend on what you put on the x axis, but they should all show no pattern, no matter what variable you provide for fitted, so pick anything that provides you with a good characteristic of the predicted signal. In your case, I would also use the mean. 

2.  Can I ask why you provide a distance matrix by hand? Normally, DHARMa will calculate the distance matrix, and it's usually only necessary to provide a distance matrix if you want to put in non-euklidian distances. If you use both coordinates and a distance matrix, the coordinates will be ignored and only used for plotting 

3. In any case, what you describe shouldn't happen, regardless of distance matrix and fitted values (fitted values are not used in the Moran's I tests). I think I can't really tell you more unless you have a reproducible example. If you don't want to post stuff here, maybe could you send me an example via email? I will treat it confidentially. 

Best
Florian

**Comment by timwilms88** [comment] 2020-03-29 07:49
Great - thanks for the quick response!

I will work on a reproducible example and be in touch with you shortly.

Best regards,

Tim

**Comment by florianhartig** [comment] 2020-04-08 18:55
Hi, OK, I have looked at this, the issue is the following:

DHARMA uses so-called randomized quantile residuals for discrete-valued, see ?simulateResiduals for explanation and references. This basically means that some noise is added to the integer values to make them smooth. A side effect of this is that residuals will change every time you re-simulate.

This confused many users in the initial release of DHARMa, similar to this question (see also https://github.com/florianhartig/DHARMa/issues/76). Moreover, I was a bit worried that people might re-simulate residuals until they have a nice-looking plot. I therefore fixed the random seed, so that each simulation produces the same result. You can overwrite this with the seed option.

What I noted now is that I forgot to fix the seed as well for recalculateResiduals and createDHARMa. I have fixed this now in https://github.com/florianhartig/DHARMa/pull/161. This will be in the next CRAN release.

Note: see also https://github.com/florianhartig/DHARMa/issues/38

**Closed** 2020-04-08 19:11 UTC
