### ISSUE TITLE
Differences between testDispersion and check_overdispersion from performance package

### ISSUE THREAD

**Issue by aureliendejode** [florianhartig/DHARMa#207] opened 2020-09-29 16:27 UTC
Hello,

I am fitting GLMM in R and want to check for over dispersion.
I used both testDispersion() and check_overdispersion() from the performance package but for the same model I get different results. testDispersion() indicating no overdispersion of the data and check_overdispersion() finding a significant overdispersion for a model with one random effect, one fixed effect and poisson family.

Any ideas why ?

Thank you

**Comment by Istalan** [comment] 2020-09-29 18:28
Hi,

This has been discussed in the open issue #117 .  
The most important part of that thread is the check_dispersion FAQ: 
http://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#testing-for-overdispersioncomputing-overdispersion-factor  
and rather you called DHARMa with refit or not.

To figure out if check_dispersion is inaccurate please show your lambdas with e.g. `hist(predict(your_model))`, also it would be good to see the actual outputs of the tests and your `sessionInfo()`.

**Comment by aureliendejode** [comment] 2020-09-30 09:26
Thanks for the quick answer.
I will read these posts. In the meantime here are what you asked for.

> check_overdispersion(glmm.poisson.depth.expo.slope.no.NA)
# Overdispersion test

       dispersion ratio =   5.217
  Pearson's Chi-Squared = 208.697
                p-value = < 0.001

Overdispersion detected.


> testDispersion(glmm.poisson.depth.expo.slope.no.NA)

	DHARMa nonparametric dispersion test via sd of residuals fitted vs. simulated

data:  simulationOutput
ratioObsSim = 1.1153, p-value = 0.544
alternative hypothesis: two.sided

hist(predict(glmm.poisson.depth.expo.slope.no.NA))
![image](https://user-images.githubusercontent.com/6107339/94667772-8a066600-030f-11eb-8641-c720116161db.png)


sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8     LC_MONETARY=fr_FR.UTF-8   
 [6] LC_MESSAGES=fr_FR.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] MuMIn_1.43.17        DHARMa_0.3.3.0       performance_0.5.0    glmmTMB_1.0.2.1      AER_1.2-9            survival_3.2-3      
 [7] sandwich_2.5-1       lmtest_0.9-37        zoo_1.8-8            car_3.0-8            sjPlot_2.8.4         effects_4.2-0       
[13] carData_3.0-4        lmerTest_3.1-2       lme4_1.1-23          Matrix_1.2-18        vcd_1.4-7            corrplot_0.84       
[19] DescTools_0.99.37    GoodmanKruskal_0.0.3 rstatix_0.6.0        ggpubr_0.4.0         extrafont_0.17       gridExtra_2.3       
[25] hrbrthemes_0.8.0     hilldiv_1.5.3        forcats_0.5.0        stringr_1.4.0        purrr_0.3.4          tibble_3.0.3        
[31] tidyverse_1.3.0      SpadeR_0.1.1         ggforce_0.3.2        dplyr_1.0.2          rlist_0.4.6.1        viridis_0.5.1       
[37] viridisLite_0.3.0    tidyr_1.1.2          readr_1.3.1          clipr_0.7.0          dada2_1.14.1         Rcpp_1.0.5          
[43] lubridate_1.7.9      iNextPD_0.3.1        iNEXT_2.0.20         ade4_1.7-15          ape_5.4              entropart_1.6-4     
[49] ggplot2_3.3.2        vegan_2.5-6          lattice_0.20-41      permute_0.9-5        rrcov_1.5-5          robustbase_0.93-6   

loaded via a namespace (and not attached):
  [1] estimability_1.3            GGally_2.0.0                lavaan_0.6-6                coda_0.19-3                
  [5] acepack_1.4.1               clusterGeneration_1.3.4     knitr_1.29                  multcomp_1.4-13            
  [9] FSA_0.8.30                  DelayedArray_0.12.3         data.table_1.13.0           rpart_4.1-15               
 [13] hwriter_1.3.2               doParallel_1.0.15           RCurl_1.98-1.2              generics_0.0.2             
 [17] BiocGenerics_0.32.0         TH.data_1.0-10              combinat_0.0-8              httpuv_1.5.4               
 [21] xml2_1.3.2                  SummarizedExperiment_1.16.1 assertthat_0.2.1            d3Network_0.5.2.1          
 [25] xfun_0.16                   hms_0.5.3                   promises_1.1.1              evaluate_0.14              
 [29] DEoptimR_1.0-8              fansi_0.4.1                 dbplyr_1.4.4                readxl_1.3.1               
 [33] igraph_1.2.5                DBI_1.1.0                   htmlwidgets_1.5.1           reshape_0.8.8              
 [37] stats4_3.6.3                ellipsis_0.3.1              subplex_1.6                 backports_1.1.8            
 [41] insight_0.9.6               survey_4.0                  pbivnorm_0.6.0              RcppParallel_5.0.2         
 [45] vctrs_0.3.4                 Biobase_2.46.0              sjlabelled_1.1.6            abind_1.4-5                
 [49] withr_2.2.0                 emmeans_1.5.1               checkmate_2.0.0             GenomicAlignments_1.22.1   
 [53] fdrtool_1.2.15              mnormt_1.5-7                phytools_0.7-47             cluster_2.1.0              
 [57] crayon_1.3.4                pkgconfig_2.0.3             labeling_0.3                tweenr_1.0.1               
 [61] GenomeInfoDb_1.22.1         nlme_3.1-148                nnet_7.3-14                 rlang_0.4.7                
 [65] lifecycle_0.2.0             extrafontdb_1.0             modelr_0.1.8                cellranger_1.1.0           
 [69] polyclip_1.10-0             matrixStats_0.56.0          phangorn_2.5.5              boot_1.3-25                
 [73] reprex_0.3.0                base64enc_0.1-3             ggridges_0.5.2              whisker_0.4                
 [77] png_0.1-7                   rjson_0.2.20                parameters_0.8.6            bitops_1.0-6               
 [81] Biostrings_2.54.0           blob_1.2.1                  ShortRead_1.44.3            jpeg_0.1-8.1               
 [85] ggeffects_0.16.0            S4Vectors_0.24.4            ggsignif_0.6.0              scales_1.1.1               
 [89] magrittr_1.5                plyr_1.8.6                  zlibbioc_1.32.0             compiler_3.6.3             
 [93] tinytex_0.24                RColorBrewer_1.1-2          plotrix_3.7-8               see_0.6.0                  
 [97] Rsamtools_2.2.3             cli_2.0.2                   XVector_0.26.0              TMB_1.7.18                 
[101] pbapply_1.4-2               htmlTable_2.0.1             Formula_1.2-3               MASS_7.3-51.6              
[105] mgcv_1.8-31                 tidyselect_1.1.0            stringi_1.4.6               mitools_2.4                
[109] latticeExtra_0.6-29         ggrepel_0.8.2               fastmatch_1.1-0             tools_3.6.3                
[113] animation_2.6               parallel_3.6.3              rio_0.5.16                  rstudioapi_0.11            
[117] foreach_1.5.0               foreign_0.8-76              geiger_2.0.7                scatterplot3d_0.3-41       
[121] farver_2.0.3                BDgraph_2.62                digest_0.6.25               shiny_1.5.0                
[125] qgam_1.3.2                  quadprog_1.5-8              GenomicRanges_1.38.0        broom_0.7.0                
[129] later_1.1.0.1               httr_1.4.2                  gdtools_0.2.2               psych_2.0.7                
[133] effectsize_0.3.3            sjstats_0.18.0              colorspace_1.4-1            rvest_0.3.5                
[137] fs_1.4.2                    IRanges_2.20.2              splines_3.6.3               statmod_1.4.34             
[141] expm_0.999-5                Exact_2.0                   systemfonts_0.2.3           xtable_1.8-4               
[145] jsonlite_1.7.0              nloptr_1.2.2.2              corpcor_1.6.9               glasso_1.11                
[149] gap_1.2.2                   R6_2.4.1                    Hmisc_4.4-0                 mime_0.9                   
[153] pillar_1.4.6                htmltools_0.5.0             fastmap_1.0.1               glue_1.4.2                 
[157] minqa_1.2.4                 BiocParallel_1.20.1         deSolve_1.28                codetools_0.2-16           
[161] maps_3.3.0                  utf8_1.1.4                  pcaPP_1.9-73                mvtnorm_1.1-1              
[165] numDeriv_2016.8-1.1         huge_1.3.4.1                curl_4.3                    gtools_3.8.2               
[169] zip_2.0.4                   openxlsx_4.1.5              Rttf2pt1_1.3.8              rmarkdown_2.3              
[173] qgraph_1.6.5                munsell_0.5.0               GenomeInfoDbData_1.2.2      iterators_1.0.12           
[177] sjmisc_2.8.5                haven_2.3.1                 reshape2_1.4.4              gtable_0.3.0               
[181] bayestestR_0.7.2

**Comment by Istalan** [comment] 2020-09-30 11:42
Huh,

your lambdas are roughly 5, so `check_overdispersion` is perfectly valid, meaning that you have very real over-dispersion in your data and you should look towards the FAQ (http://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#fitting-models-with-overdispersion) to change your model. 

Please stick around though, as there appears to be real issue with DHARMa not detecting the over-dispersion and @florianhartig should probably take a look at it.

**Comment by florianhartig** [comment] 2020-09-30 11:45
Hi @aureliendejode - could you post your model / data here, or send it to me privately? I can have a look then. Cheers,
Florian

**Comment by florianhartig** [comment] 2020-09-30 11:46
p.s. - as said elsewhere, a n.s. in a hypothesis test does not mean that there is no Overdispersion, it just means that it was not possible to show that there is overdispersion, so the tests are not really in disagreement

**Comment by aureliendejode** [comment] 2020-10-01 12:30
Hello,
Thanks to both of you for your help.
I moved on to a negative binomial function and used Dharma  to check the residuals and the overdisp_fun from the post @Istalan sent. 
Here are the results. They look good to me so I think this model should be ok.
overdisp_fun(glmm.bn.depth.no.NA)
     chisq      ratio        rdf          p 
34.6351436  0.8246463 42.0000000  0.7829169 

testDispersion(glmm.bn.depth.no.NA)

	DHARMa nonparametric dispersion test via sd of residuals fitted vs. simulated

data:  simulationOutput
ratioObsSim = 1.0718, p-value = 0.584
alternative hypothesis: two.sided

![image](https://user-images.githubusercontent.com/6107339/94809245-99121480-03f2-11eb-8829-418fcfed363e.png)


I also tested for zero inflated just in case but everything looks fine except that the graph is a bit weird...

testZeroInflation(glmm.bn.depth.no.NA)

	DHARMa zero-inflation test via comparison to expected zeros with simulation under H0 = fitted model

data:  simulationOutput
ratioObsSim = NaN, p-value = 1
alternative hypothesis: two.sided


@florianhartig I sent you my dataset and command using the mail did you receive it ?

Again thanks for your help

**Comment by florianhartig** [comment] 2020-10-02 08:35
Hi @aureliendejode - no, I didn't receive the data, did you send it to my university mail (see https://www.uni-regensburg.de/biologie-vorklinische-medizin/theoretische-oekologie/mitarbeiter/hartig/index.html)?

**Comment by florianhartig** [comment] 2020-10-02 09:06
Hi @aureliendejode - I have looked at your example, and the issue is basically what I suspected, which is that the overdispersion doesn't come out because the default in DHARMa is to simulate new data while re-simulating REs (so-called unconditional simulation), which tends to make the dispersion test less sensitive. The solution is to re-simulate with conditional residuals. This is noted in the help of testDispersion, but I realize it's not very intuitive for the user, and maybe I should throw a  warning or implement some functions to automatically choose the unconditional residuals. Anyway, if you calculate the dispersion test based on unconditional residuals, it is also significant in DHARMa

```
res <- simulateResiduals(m1, re.form = NULL)
testDispersion(res)
```

**Comment by aureliendejode** [comment] 2020-10-02 09:15
I'll have a deeper look into the help and documentation.
Thanks

**Comment by florianhartig** [comment] 2020-10-05 11:09
Sure. As I said, the bottomline is that it's certainly better to continue with the negative binomial. I'll close this issue, but will add a new issue to better document the options in the testDispersion function.

**Closed by florianhartig** 2020-10-05 11:09 UTC
Labels: question

**Comment by florianhartig** [comment] 2020-10-05 11:11
Actually, I think #117 is already sufficient as a reminder, so I'll leave it there.

**Comment by florianhartig** [comment] 2020-10-05 11:12
oh, and I see there is also #201
