### ISSUE TITLE
error with running gam model for small dataset

### ISSUE THREAD

**Issue by milliongodana** [florianhartig/DHARMa#344] opened 2022-08-12 09:38 UTC
I would appreciate if anyone has a solution for this kind of error in running gam model

Error in smooth.construct.tp.smooth.spec(object, dk$data, dk$knots): A term has fewer unique covariate combinations than specified maximum degrees of freedom

**Comment by florianhartig** [comment] 2022-08-22 13:59
Hello,

this is a duplicate of #145, please have a look there. 

Best,
Florian

**Closed by florianhartig** 2022-08-22 13:59 UTC
Labels: duplicate
