### ISSUE TITLE
getSimulations fails for COMPoisson family

### ISSUE THREAD

**Issue by seanhardison1** [florianhartig/DHARMa#160] opened 2020-04-08 16:57 UTC
Hi Florian,

Thanks for putting together such an easy to use and helpful package.

I'm trying to simulate from a COMPoisson GLM using `simulateResiduals()`, but the function seems to be breaking on the `getSimulations` step. Here's a reproducible example using `spaMM`

```
library(spaMM)
library(DHARMa)

data("freight")
mod <- glm(broken ~ transfers, data=freight, family = COMPoisson(nu=2))
family(mod)
simulateResiduals(mod)
```
Any ideas on a fix? 

best

Sean

**Comment by florianhartig** [comment] 2020-04-08 19:05
Hi Sean,

OK, the problem is on the spaMM side, it seems the simulate function is not implemented or does not work for this family. I didn't know this, so I'm not checking for it. 

```
library(spaMM)

data("freight")

mod <- HLfit(broken ~ transfers, data=freight, family = poisson)
simulate(mod,2)

mod <- fitme(broken ~ transfers, data=freight, family = COMPoisson(nu=2))
simulate(mod,2)

mod <- glm(broken ~ transfers, data=freight, family = COMPoisson(nu=2))
simulate(mod,2)

mod <- HLfit(broken ~ transfers, data=freight, family = COMPoisson(nu=2))
simulate(mod,2)
```
I'll ask the developer if this is intended / documented.

The only workaround (until a simulate option is implemented) would be https://github.com/florianhartig/DHARMa/wiki/Adding-new-R-packages-to-DHARMA#how-to-do-hand-coded-simulations-for-unsupported-models

**Comment by f-rousset** [comment] 2020-04-09 08:57
Hi,
thanks for pointing this. The problem is indeed in spaMM and a fixed version is coming soon. `simulate` has actually been implemented for COMPoisson family, but it's broken now. In addition, I had thought about simulating from an `HLfit` object but not from a `glm` object with COMPoisson family. This also appears easy to fix.

Best,
F.

**Comment by florianhartig** [comment] 2020-04-09 09:53
Hi Francois,

thanks for the info! 

I'll keep this issue open until fixed in spaMM, so that I can test, but for the moment, I do not intend to do anything on the DHARMa side, because this is hopefully fixed soon!

Best
Florian

**Comment by f-rousset** [comment] 2020-04-09 23:06
The problems are fixed in the development version of spaMM, which can be downloaded (for 3 days) from the following address
https://filesender.renater.fr/?s=download&token=42cad4f1-24b8-4c35-9d42-2b281625b55b
Best,
F.

**Comment by seanhardison1** [comment] 2020-04-10 01:51
Thank you @f-rousset and @florianhartig!! The new simulate method works great.

**Comment by florianhartig** [comment] 2020-04-10 07:19
Excellent, will close!

**Closed by florianhartig** 2020-04-10 07:19 UTC
Labels: packageSupport, spaMM
