### ISSUE TITLE
glm.nb from package MASS

### ISSUE THREAD

**Issue by alireza202** [florianhartig/DHARMa#5] opened 2016-10-07 01:13 UTC
When I try to use glm.nb, I get the message:

> Warning message:
> In simulateResiduals(fittedModel = fittedModel, n = 250): DHARMa: fittedModel not in class of supported models. Absolutely no guarantee that this will work!

Do you think the results are still ok?

**Comment by florianhartig** [comment] 2016-10-07 07:57
This is a duplicate of https://github.com/florianhartig/DHARMa/issues/4

The message appears because I had not checked the nb model classes yet. 

I have now done some preliminary checks and everything seemed to work perfectly, so I would say it's OK to use it. I will do some more checks and then remove the warning in the next CRAN update.

**Comment by florianhartig** [comment] 2016-10-07 07:59
Sorry, it's not really a duplicate of https://github.com/florianhartig/DHARMa/issues/4 because https://github.com/florianhartig/DHARMa/issues/4 is about glmer.nb, but I checked both glmer.nb and MASS::glm.nb and both seemed to work fine.

**Comment by alireza202** [comment] 2016-10-09 05:27
Thanks!

**Comment by florianhartig** [comment] 2016-10-11 09:03
One important add-on: as noted by Jochen Fründ, because neg.binomial was not in the list of supported models, the default setting for integerResponse in simulateResiduals was F. But neg.binom is integer, so it should be set to T, otherwise residuals will not be totally flat for low counts. 

This is now fixed in https://github.com/florianhartig/DHARMa/commit/08594c5cbd950f108bc301bf289cbe49b1eb5389 and will be included in the next CRAN release 0.1.1.

* If you are working with the development version as explained in https://github.com/florianhartig/DHARMa this you are fine. 

* If you are working working with the current CRAN release https://github.com/florianhartig/DHARMa/releases/tag/v0.1, you should set integerResponse = T in simulateResiduals to avoid problems!

**Comment by florianhartig** [comment] 2016-11-19 19:31
This was fully fixed in https://github.com/florianhartig/DHARMa/releases/tag/v0.1.1 and is now on CRAN

**Closed by florianhartig** 2016-11-19 19:31 UTC
