### ISSUE TITLE
Problem with plot against the predictor

### ISSUE THREAD

**Issue by Olivia-Jean** [florianhartig/DHARMa#338] opened 2022-06-14 21:32 UTC
Hello,

I am trying to run the code described in the section "Detecting missing predictors or wrong functional assumptions" from (https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html#detecting-missing-predictors-or-wrong-functional-assumptions).

I am using lmer() to run a model which has a Time x Study Condition interaction with a random slope for time and random intercept for participant ID. Time is numeric 0-3, study condition is a factor with 2 levels, and participant ID is a character. There are NAs in the outcome but none for the predictors (long format). 

I tried using the following code:
`lmer.model = lmer(QOLmental ~ Time*StudyCondition + (1 + Time | participant_id), data = data)
simulationOutput = simulateResiduals(lmer.model)
par(mfrow = c(1,2))
plotResiduals(simulationOutput, data$Time)
plotResiduals(simulationOutput, data$StudyCondition)`

But I got this error:
Error in ensurePredictor(simulationOutput, form) : 
DHARMa: residuals and predictor do not have the same length. The issue is possibly that you have NAs in your predictor that were removed during the model fit. Remove the NA values from your predictor.

I double checked that there are no NA values in either Time nor study condition.

Is this a bug? I am using DHARMa version 0.4.5 and lme4 version 1.1-29.

Please let me know what other information I can give to help. 

Thanks,

Olivia

**Comment by florianhartig** [comment] 2022-06-15 07:36
Hello Olivia,

could you send me the data for this, ideally directly here, or else (if confidential) via email?

Cheers,
Florian

**Comment by florianhartig** [comment] 2022-06-16 12:44
yes, I can reproduce this - the issue is that you have an NA in your data - remember that all NA rows are discarded in the lm, so you have to provide the same data in plotResiduals that is used in the model. The easiest ways to do this would be 

1. do a complete.cases() before fitting the regression, to remove the NA lines from your data 
2. you can also extras the data that was used to fit them model via model.frame()

```
x = model.frame(model)
plotResiduals(simulationOutput, x$Time)

```

I know this is all not sure convenient, and it's on my list to provide a bit more help on this for the user, but at the moment this is how it is. 

Best,
Florian

**Comment by Olivia-Jean** [comment] 2022-06-16 14:38
Ah, thank you for that explanation and the work around to use model.frame!

**Comment by florianhartig** [comment] 2022-06-18 10:40
Glad this was helpful. I will close the issue!

**Closed by florianhartig** 2022-06-18 10:40 UTC
