### ISSUE TITLE
simulateResiduals fails on glmmTMB model with rank_check = "adjust"

### ISSUE THREAD

**Issue by gordy2x** [florianhartig/DHARMa#373] opened 2023-03-17 02:01 UTC
There is now a (optional) argument in glmmTMB that drops terms that make the design matrix rank-deficient (see https://github.com/glmmTMB/glmmTMB/issues/522#issuecomment-1472885734), this is what lme4 does by default. I can run simulateResiduals on an lme4 object but not on a glmmTMB object with rank_check = "adjust".

```
library(glmmTMB)
library(lme4)
library(DHARMa)
set.seed(101)
dd <- data.frame(z = rnorm(100), 
                 x1 = 1:100, x2 = 2:101,
                 re = rep(1:20, each = 5))

mod_lme4 <- lmer(z ~ x1 + x2 + (1|re), data = dd)
simulateResiduals(mod_lme4, n = 5)


mod_TMB <- glmmTMB(z ~ x1 + x2 + (1|re), data = dd, 
                   control = glmmTMBControl(rank_check = "adjust"))
simulateResiduals(mod_TMB, n = 5)
```

**Comment by florianhartig** [comment] 2023-03-28 13:37
Thanks Reinier ... I'll leave it open for now to check later if this has been fixed in glmMTMB, but will likely not address this in DHARMa.

**Comment by bbolker** [comment] 2023-05-06 21:03
When I try this with `remotes::install_github("glmmTMB/glmmTMB/glmmTMB@rankdef_NA")` (which returns a covariance matrix with `NA` values filled in for the coefficients that have been dropped for rank-deficiency) I get:

> Error in checkModelMatrix(getX(data.tmb1), getX(data.tmb0)) : 
  Prediction is not possible for unknown fixed effects: x2
Probably some factor levels in 'newdata' require fitting a new model.

I'm happy to try to adjust some behaviour on the `glmmTMB` side, but I'm not sure what would help ...

I'm not sure what the issue is here; `glmmTMB` now returns fixed-effects coefficients and covariance matrices with the same filled-in `NA` pattern as `lm` does (which works), and `getME(mod_TMB, "X")` returns a matrix with the columns dropped ... 

I started to look at `getX` within the code (why isn't it using `getME()` ... ?), but ran out of steam.

**Comment by florianhartig** [comment] 2023-05-08 07:22
Hi Ben, many thanks! I'll keep this open until the problem is resolved in CRAN!

**Comment by reiniervlinschoten** [comment] 2023-05-08 08:28
Awesome, thank you very much for fixing this!

**Closed** 2024-10-10 09:08 UTC
Labels: wontfix, glmmTMB
